version: "3.3"
services:
  api:
    image: "$IMAGE_REGISTRY/$IMAGE_NAME@$IMAGE_DIGEST"
    container_name: api
    environment:
    - NODE_ENV=production
    restart: on-failure
    ports:
      - "3000:3000"
    volumes:
      - db-data:/var/opt/travel-log:rw

volumes:
  db-data:
    name: travel-log-data